import type { ToolPlanId } from "@/types/audit";

export type BillingUnit = "per_seat" | "flat" | "usage" | "unknown";

export interface PricingEntry {
  planId: ToolPlanId;
  vendor: string;
  tool: string;
  planName: string;
  /** Monthly price in USD. For usage-based or contact-sales plans, set to null. */
  priceMonthlyUsd: number | null;
  billingUnit: BillingUnit;
  officialUrl: string;
  verifiedAt: string; // YYYY-MM-DD
}

export type PricingTable = Record<ToolPlanId, PricingEntry>;

// IMPORTANT: Every numeric entry must be documented in PRICING_DATA.md.
export const PRICING: PricingTable = {
  cursor_hobby: {
    planId: "cursor_hobby",
    vendor: "Cursor",
    tool: "Cursor",
    planName: "Hobby",
    priceMonthlyUsd: 0,
    billingUnit: "per_seat",
    officialUrl: "https://cursor.com/pricing",
    verifiedAt: "2026-05-08",
  },
  cursor_pro: {
    planId: "cursor_pro",
    vendor: "Cursor",
    tool: "Cursor",
    planName: "Pro",
    priceMonthlyUsd: 20,
    billingUnit: "per_seat",
    officialUrl: "https://cursor.com/pricing",
    verifiedAt: "2026-05-08",
  },
  cursor_business: {
    planId: "cursor_business",
    vendor: "Cursor",
    tool: "Cursor",
    planName: "Business",
    priceMonthlyUsd: 40,
    billingUnit: "per_seat",
    officialUrl: "https://cursor.com/pricing",
    verifiedAt: "2026-05-08",
  },
  cursor_enterprise: {
    planId: "cursor_enterprise",
    vendor: "Cursor",
    tool: "Cursor",
    planName: "Enterprise",
    priceMonthlyUsd: null,
    billingUnit: "unknown",
    officialUrl: "https://cursor.com/pricing",
    verifiedAt: "2026-05-08",
  },

  copilot_individual: {
    planId: "copilot_individual",
    vendor: "GitHub",
    tool: "GitHub Copilot",
    planName: "Individual",
    priceMonthlyUsd: 10,
    billingUnit: "per_seat",
    officialUrl: "https://github.com/features/copilot/plans",
    verifiedAt: "2026-05-08",
  },
  copilot_business: {
    planId: "copilot_business",
    vendor: "GitHub",
    tool: "GitHub Copilot",
    planName: "Business",
    priceMonthlyUsd: 19,
    billingUnit: "per_seat",
    officialUrl: "https://github.com/features/copilot/plans",
    verifiedAt: "2026-05-08",
  },
  copilot_enterprise: {
    planId: "copilot_enterprise",
    vendor: "GitHub",
    tool: "GitHub Copilot",
    planName: "Enterprise",
    priceMonthlyUsd: 39,
    billingUnit: "per_seat",
    officialUrl: "https://github.com/features/copilot/plans",
    verifiedAt: "2026-05-08",
  },

  claude_free: {
    planId: "claude_free",
    vendor: "Anthropic",
    tool: "Claude",
    planName: "Free",
    priceMonthlyUsd: 0,
    billingUnit: "per_seat",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },
  claude_pro: {
    planId: "claude_pro",
    vendor: "Anthropic",
    tool: "Claude",
    planName: "Pro",
    priceMonthlyUsd: 20,
    billingUnit: "per_seat",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },
  claude_max: {
    planId: "claude_max",
    vendor: "Anthropic",
    tool: "Claude",
    planName: "Max",
    priceMonthlyUsd: 100,
    billingUnit: "per_seat",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },
  claude_team: {
    planId: "claude_team",
    vendor: "Anthropic",
    tool: "Claude",
    planName: "Team",
    priceMonthlyUsd: 30,
    billingUnit: "per_seat",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },
  claude_enterprise: {
    planId: "claude_enterprise",
    vendor: "Anthropic",
    tool: "Claude",
    planName: "Enterprise",
    priceMonthlyUsd: null,
    billingUnit: "unknown",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },
  claude_api: {
    planId: "claude_api",
    vendor: "Anthropic",
    tool: "Claude",
    planName: "API direct",
    priceMonthlyUsd: null,
    billingUnit: "usage",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },

  chatgpt_plus: {
    planId: "chatgpt_plus",
    vendor: "OpenAI",
    tool: "ChatGPT",
    planName: "Plus",
    priceMonthlyUsd: 20,
    billingUnit: "per_seat",
    officialUrl: "https://openai.com/chatgpt/pricing",
    verifiedAt: "2026-05-08",
  },
  chatgpt_team: {
    planId: "chatgpt_team",
    vendor: "OpenAI",
    tool: "ChatGPT",
    planName: "Team",
    priceMonthlyUsd: 30,
    billingUnit: "per_seat",
    officialUrl: "https://openai.com/chatgpt/pricing",
    verifiedAt: "2026-05-08",
  },
  chatgpt_enterprise: {
    planId: "chatgpt_enterprise",
    vendor: "OpenAI",
    tool: "ChatGPT",
    planName: "Enterprise",
    priceMonthlyUsd: null,
    billingUnit: "unknown",
    officialUrl: "https://openai.com/chatgpt/pricing",
    verifiedAt: "2026-05-08",
  },
  chatgpt_api: {
    planId: "chatgpt_api",
    vendor: "OpenAI",
    tool: "OpenAI API",
    planName: "API direct",
    priceMonthlyUsd: null,
    billingUnit: "usage",
    officialUrl: "https://openai.com/api/pricing",
    verifiedAt: "2026-05-08",
  },

  anthropic_api: {
    planId: "anthropic_api",
    vendor: "Anthropic",
    tool: "Anthropic API",
    planName: "API direct",
    priceMonthlyUsd: null,
    billingUnit: "usage",
    officialUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-08",
  },
  openai_api: {
    planId: "openai_api",
    vendor: "OpenAI",
    tool: "OpenAI API",
    planName: "API direct",
    priceMonthlyUsd: null,
    billingUnit: "usage",
    officialUrl: "https://openai.com/api/pricing",
    verifiedAt: "2026-05-08",
  },

  gemini_pro: {
    planId: "gemini_pro",
    vendor: "Google",
    tool: "Gemini",
    planName: "Pro",
    priceMonthlyUsd: 19.99,
    billingUnit: "per_seat",
    officialUrl: "https://one.google.com/about/google-ai-plans/",
    verifiedAt: "2026-05-08",
  },
  gemini_ultra: {
    planId: "gemini_ultra",
    vendor: "Google",
    tool: "Gemini",
    planName: "Ultra",
    priceMonthlyUsd: 29.99,
    billingUnit: "per_seat",
    officialUrl: "https://one.google.com/about/google-ai-plans/",
    verifiedAt: "2026-05-08",
  },
  gemini_api: {
    planId: "gemini_api",
    vendor: "Google",
    tool: "Gemini API",
    planName: "API",
    priceMonthlyUsd: null,
    billingUnit: "usage",
    officialUrl: "https://ai.google.dev/pricing",
    verifiedAt: "2026-05-08",
  },

  windsurf_free: {
    planId: "windsurf_free",
    vendor: "Codeium",
    tool: "Windsurf",
    planName: "Free",
    priceMonthlyUsd: 0,
    billingUnit: "per_seat",
    officialUrl: "https://codeium.com/windsurf",
    verifiedAt: "2026-05-08",
  },
  windsurf_pro: {
    planId: "windsurf_pro",
    vendor: "Codeium",
    tool: "Windsurf",
    planName: "Pro",
    priceMonthlyUsd: 15,
    billingUnit: "per_seat",
    officialUrl: "https://codeium.com/windsurf",
    verifiedAt: "2026-05-08",
  },
  windsurf_team: {
    planId: "windsurf_team",
    vendor: "Codeium",
    tool: "Windsurf",
    planName: "Team",
    priceMonthlyUsd: null,
    billingUnit: "unknown",
    officialUrl: "https://codeium.com/windsurf",
    verifiedAt: "2026-05-08",
  },
};
